server:
  port: 8080

spring:
  application:
    name: pact-mock-provider
  
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    uk.gov.justice.laa.datastewardship.payments.pact: DEBUG
    au.com.dius.pact: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
