name: "Delete K8s Resources by Label"
description: "Deletes all Kubernetes resources with a given Helm release name and namespace"

inputs:
  release:
    description: "Helm release name (label value)"
    required: true
  kube_namespace:
    description: "Kubernetes namespace"
    required: true

runs:
  using: "composite"
  steps:

  - name: Uninstall Helm release
    shell: bash
    run: helm uninstall ${{ inputs.release }} --namespace ${{ inputs.kube_namespace }}
