name: "Delete K8s Resources by Label"
description: "Deletes all Kubernetes resources with a given Helm release name and namespace"

inputs:
  release:
    description: "Helm release name (label value)"
    required: true
  kube_namespace:
    description: "Kubernetes namespace"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Delete all and extended resources
      shell: bash
      run: |
        echo "Deleting all preview resources in namespace '${{ inputs.kube_namespace }}' with label 'release=${{ inputs.release }}'"

        RESOURCES=(
          all
          ingress
          configmap
          secret
          pvc
          job
          cronjob
          serviceaccount
          role
          rolebinding
        )

        for r in "${RESOURCES[@]}"; do
          echo "Deleting $r..."
          kubectl delete "$r" -n "${{ inputs.kube_namespace }}" -l "release=${{ inputs.release }}" --ignore-not-found
        done

        echo "Cleanup complete."