# Default values for data-stewardship-payments.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# TODO:
# Increase replicaCount pre launch
# staging and production replicaCount value should matach
replicaCount: 1

image:
  repository: null
  tag: null

service_account:
  name: laa-data-stewardship-civil-claims-api-staging-service-account

service:
  type: ClusterIP
  port: 8080

ingress:
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "laa-data-stewardship-civil-claims-api-dsp-chart-laa-data-stewardship-civil-claims-api-staging-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
  hosts:
    - laa-data-stewardship-civil-claims-api-staging.apps.live.cloud-platform.service.justice.gov.uk
  tls:
    - hosts:
      - domain: laa-data-stewardship-civil-claims-api-staging.apps.live.cloud-platform.service.justice.gov.uk

resources:
  limits:
    cpu: 500m
    memory: 1G
  requests:
    cpu: 10m
    memory: 125Mi
