# Default values for data-stewardship-payments.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: null
  tag: null

service_account:
  name: laa-data-stewardship-civil-claims-api-uat-service-account

service:
  type: ClusterIP
  port: 8080

ingress:
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "laa-data-stewardship-civil-claims-api-dsp-chart-laa-data-stewardship-civil-claims-api-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
  hosts: []

resources:
  limits:
    cpu: 500m
    memory: 1G
  requests:
    cpu: 10m
    memory: 125Mi
