name: "Get merged release name"
description: 'Get the release name for the PR that has just been closed or merged into Main branch'

outputs:
  merged-branch-name:
    description: "Extracted merged branch name"
    value: ${{ steps.extract_branch.outputs.branch_name }}
  merged-release-name:
    description: "Extracted merged release name"
    value: ${{ steps.extract_release.outputs.release_name }}

runs:
  using: "composite"
  steps:

    - name: Get branch name for the merged/closed PR
      id: get_pr_branch
      shell: bash
      run: |
        echo "Merged/closed branch was: ${{ github.event.pull_request.head.ref }}"
        echo "BRANCH_NAME=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT

    - name: Extract release name from branch name
      id: extract_release
      uses: ./.github/actions/extract_release_name_from_branch
      with:
        branch_name: ${{ steps.get_pr_branch.outputs.branch_name }}
