name: "Get merged release name"
description: 'Get a release name that has just been merged into Main branch'

outputs:
  merged-branch-name:
    description: "Extracted merged branch name"
    value: ${{ steps.extract_branch.outputs.branch_name }}
  merged-release-name:
    description: "Extracted merged release name"
    value: ${{ steps.extract_release.outputs.release_name }}

runs:
  using: "composite"
  steps:

    - name: Extract merged branch name
      id: extract_branch
      shell: bash
      run: |
        echo "BRANCH_NAME=$(git log -1 --pretty=%B | grep -oE 'Merge pull request #[0-9]+ from .*/(.*)' | awk '{print $NF}' | sed 's#^[^/]*/##')" >> $GITHUB_OUTPUT

    - name: Extract release name from branch name
      id: extract_release
      uses: ./.github/actions/extract_release_name_from_branch
      with:
        branch_name: ${{ steps.extract_branch.outputs.branch_name }}
