apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-stewardship-payments.fullname" . }}
  labels:
    {{- include "data-stewardship-payments.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  selector:
    matchLabels:
      {{- include "data-stewardship-payments.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "data-stewardship-payments.selectorLabels" . | nindent 8 }}
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
    spec:
      serviceAccountName: "{{ .Values.service_account.name }}"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: [ "ALL" ]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
